baseURL = 'http://blog.kfegar.fr/'
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
theme = "anatole"
title = 'Blog'

[params]
title = 'Blog de Kevin Fégar'
author = "Kevin Fégar"
description = "Développeur web rennais, touche à tout et curieux"
profilePicture = "images/profile.jpg"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/kevin-fegar/"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:kevin.fegar@gmail.com"
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/headward/"